### ISSUE TITLE
Organisations not fetched in dropdown box when creating dataset

### ISSUE THREAD

**Issue by Nithyavasudevan** [okfn/ckanext-glasgow#66]
1. Logged in as SuperAdmin and navigated to create dataset screen. 
2. Filled in all the mandatory fields.
3. Tried to select an organisation from the dropdown list.
4. Aberdeen School of Art was listed by default and no other organisations were present.
5. Tried to search for Microsoft which is an organisation present in the platform and listed as one of the organisations within CKAN. But search results were empty.
   ![image](https://cloud.githubusercontent.com/assets/7315913/3355489/949290e6-fab3-11e3-9506-23449bb55edf.png)
6. Organisation should have been marked as a mandatory field.

**Comment by amercader** [comment]
The user management side of the auth process is not yet implemented (neither in the EC API or the CKAN side of things).

This means that when you log in with a WAAD user, CKAN has still no way of knowing that a) this user is a superadmin or b) which organizations this user belongs to. Right now the user is created as a normal user without rights in any organization.

The reason Aberdeen School of Art comes up is because we [manually added](https://ckanfrontend.cloudapp.net/organization/members/aberdeen-school-of-art) a couple of WAAD users as administrators of this organizations, so you would be able to test things like creating a dataset / uploading a file.

Apologies if this caused confusion, but until we can't replicate the existing user and roles on the platform we need to use workarounds like this one.

**Comment by amercader** [comment]
BTW we only added the users that already existed in the CKAN DB, which are 
- None None (I assume that's the superadmin you mention)
- Editor GCC2

If you log in with another one we will need to add this manually to the org.

**Comment by Nithyavasudevan** [comment]
What is the userid for this None None?

The id i used is SuperAdmin1@GCCCTPECADINT.onmicrosoft.com

**Comment by amercader** [comment]
Logging in as a superadmin now displays all organizations in the New Datasets Organization field:

https://ckanfrontend.cloudapp.net/dataset/new

**Comment by Nithyavasudevan** [comment]
I can now see the values in the dropdown, but it still needs to be marked as a mandatory field and it should not default a value. The user should consciously select a value.

**Comment by amercader** [comment]
Org field flagged as mandatory, not selected by default (except when user belongs to only one organization).
Deployed to sandbox.
